SELECT TOP (1000) [id]
      ,[Descripcion]
      ,[FechaConsulta]
      ,[DiagnosticoInicial]
      ,[DiagnosticoDefinitivo]
      ,[PacienteId]
      ,[PlantillaId]
      ,[ProblemaId]
      ,[EstadoProblemaId]
      ,[MedicoId]
  FROM [UPECLINICA].[dbo].[Evolucion]